## Challenge #181: Ingredients of an Old Southern

Original challenge: https://community.alteryx.com/t5/Weekly-Challenge/Challenge-181-Ingredients-of-an-Old-Southern/td-p/464549

Using the provided URL, download and parse the data in the recipe for an Old Southern. Create a list of the cocktail ingredients and measurements.

In [174]:
import pandas as pd
import requests, io
import json

In [175]:
df = pd.read_csv(".Challenge 181/challenge_181_input.csv")
df

                                                                   Field1
0  https://www.thecocktaildb.com/api/json/v1/1/search.php?s=Old Fashioned

In [176]:
#Get data in JSON format from URL
urlData = requests.get(df.loc[0]["Field1"]).content
urlData

b'{"drinks":[{"idDrink":"11001","strDrink":"Old Fashioned","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,Classic,Alcoholic,Expensive","strVideo":null,"strCategory":"Cocktail","strIBA":"Unforgettables","strAlcoholic":"Alcoholic","strGlass":"Old-fashioned glass","strInstructions":"Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.\\r\\nFill the glass with ice cubes and add whiskey.\\r\\n\\r\\nGarnish with orange twist, and a cocktail cherry.","strInstructionsES":null,"strInstructionsDE":"Zuckerw\\u00fcrfel in ein old fashioned Glas geben und mit Bitterstoff s\\u00e4ttigen, einen Schuss Wasser hinzuf\\u00fcgen. Vermischen, bis sie sich aufl\\u00f6sen.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"https:\\/\\/www.thecocktaildb.com\\/images\\/media\\/drink\\/vrwquq1478252802.jpg","strIngredient1":"Bourbon","strIngredient2":"Angostura bitters","strIngredient3":"Sugar","strIngredient4":"Water","strIngredient5":null,"strIngredient6":null,"strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"4.5 cL","strMeasure2":"2 dashes","strMeasure3":"1 cube","strMeasure4":"dash","strMeasure5":null,"strMeasure6":null,"strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"Yes","dateModified":"2016-11-04 09:46:42"}]}'

In [177]:
#Convert bytes into dictionary
jsonResponse = json.loads(urlData.decode('utf-8'))
jsonResponse

{'drinks': [{'idDrink': '11001',
   'strDrink': 'Old Fashioned',
   'strDrinkAlternate': None,
   'strDrinkES': None,
   'strDrinkDE': None,
   'strDrinkFR': None,
   'strDrinkZH-HANS': None,
   'strDrinkZH-HANT': None,
   'strTags': 'IBA,Classic,Alcoholic,Expensive',
   'strVideo': None,
   'strCategory': 'Cocktail',
   'strIBA': 'Unforgettables',
   'strAlcoholic': 'Alcoholic',
   'strGlass': 'Old-fashioned glass',
   'strInstructions': 'Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.\r\nFill the glass with ice cubes and add whiskey.\r\n\r\nGarnish with orange twist, and a cocktail cherry.',
   'strInstructionsES': None,
   'strInstructionsDE': 'Zuckerwürfel in ein old fashioned Glas geben und mit Bitterstoff sättigen, einen Schuss Wasser hinzufügen. Vermischen, bis sie sich auflösen.',
   'strInstructionsFR': None,
   'strInstructionsZH-HANS': None,
   'strInstructionsZH-HANT': None,
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg',
   'strIngredient1': 'Bourbon',
   'strIngredient2': 'Angostura bitters',
   'strIngredient3': 'Sugar',
   'strIngredient4': 'Water',
   'strIngredient5': None,
   'strIngredient6': None,
   'strIngredient7': None,
   'strIngredient8': None,
   'strIngredient9': None,
   'strIngredient10': None,
   'strIngredient11': None,
   'strIngredient12': None,
   'strIngredient13': None,
   'strIngredient14': None,
   'strIngredient15': None,
   'strMeasure1': '4.5 cL',
   'strMeasure2': '2 dashes',
   'strMeasure3': '1 cube',
   'strMeasure4': 'dash',
   'strMeasure5': None,
   'strMeasure6': None,
   'strMeasure7': None,
   'strMeasure8': None,
   'strMeasure9': None,
   'strMeasure10': None,
   'strMeasure11': None,
   'strMeasure12': None,
   'strMeasure13': None,
   'strMeasure14': None,
   'strMeasure15': None,
   'strCreativeCommonsConfirmed': 'Yes',
   'dateModified': '2016-11-04 09:46:42'}]}

In [178]:
#Acces values in "drinks" key and add them to a DataFrame
df2 = pd.DataFrame(jsonResponse["drinks"][0], index = [0])
df2

,idDrink,strDrink,strDrinkAlternate,strDrinkES,strDrinkDE,strDrinkFR,strDrinkZH-HANS,strDrinkZH-HANT,strTags,strVideo,...,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strCreativeCommonsConfirmed,dateModified
0,11001,Old Fashioned,None,None,None,None,None,None,"IBA,Classic,Alcoholic,Expensive",None,...,None,None,None,None,None,None,None,None,Yes,2016-11-04 09:46:42

In [179]:
#Pivot DataFrame to enable easier filtering
df2 = pd.melt(df2)
df2

,variable,value
0,idDrink,11001
1,strDrink,Old Fashioned
2,strDrinkAlternate,None
3,strDrinkES,None
4,strDrinkDE,None
5,strDrinkFR,None
6,strDrinkZH-HANS,None
7,strDrinkZH-HANT,None
8,strTags,"IBA,Classic,Alcoholic,Expensive"
9,strVideo,None
10,strCategory,Cocktail
11,strIBA,Unforgettables
12,strAlcoholic,Alcoholic
13,strGlass,Old-fashioned glass
14,strInstructions,"Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Mu..."
15,strInstructionsES,None
16,strInstructionsDE,"Zuckerwürfel in ein old fashioned Glas geben und mit Bitterstoff sättigen, einen Schuss Wasser h..."
17,strInstructionsFR,None
18,strInstructionsZH-HANS,None
19,strInstructionsZH-HANT,None
20,strDrinkThumb,https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg
21,strIngredient1,Bourbon
22,strIngredient2,Angostura bitters
23,strIngredient3,Sugar
24,strIngredient4,Water
25,strIngredient5,None
26,strIngredient6,None
27,strIngredient7,None
28,strIngredient8,None
29,strIngredient9,None
30,strIngredient10,None
31,strIngredient11,None
32,strIngredient12,None
33,strIngredient13,None
34,strIngredient14,None
35,strIngredient15,None
36,strMeasure1,4.5 cL
37,strMeasure2,2 dashes
38,strMeasure3,1 cube
39,strMeasure4,dash
40,strMeasure5,None
41,strMeasure6,None
42,strMeasure7,None
43,strMeasure8,None
44,strMeasure9,None
45,strMeasure10,None
46,strMeasure11,None
47,strMeasure12,None
48,strMeasure13,None
49,strMeasure14,None
50,strMeasure15,None
51,strCreativeCommonsConfirmed,Yes
52,dateModified,2016-11-04 09:46:42

In [180]:
#Exclude null values
df2 = df2[df2["value"].notnull()]
df2.head(20)

,variable,value
0,idDrink,11001
1,strDrink,Old Fashioned
8,strTags,"IBA,Classic,Alcoholic,Expensive"
10,strCategory,Cocktail
11,strIBA,Unforgettables
12,strAlcoholic,Alcoholic
13,strGlass,Old-fashioned glass
14,strInstructions,"Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Mu..."
16,strInstructionsDE,"Zuckerwürfel in ein old fashioned Glas geben und mit Bitterstoff sättigen, einen Schuss Wasser h..."
20,strDrinkThumb,https://www.thecocktaildb.com/images/media/drink/vrwquq1478252802.jpg
21,strIngredient1,Bourbon
22,strIngredient2,Angostura bitters
23,strIngredient3,Sugar
24,strIngredient4,Water
36,strMeasure1,4.5 cL
37,strMeasure2,2 dashes
38,strMeasure3,1 cube
39,strMeasure4,dash
51,strCreativeCommonsConfirmed,Yes
52,dateModified,2016-11-04 09:46:42

In [181]:
#Keep rows which contain ingredients and measures
ingredient = df2[df2["variable"].str.contains("Ingredient")]
measure = df2[df2["variable"].str.contains("Measure")]

In [182]:
#Extract number from variable to use as key for join
ingredient["id"] = ingredient["variable"].str.extract("(\d)")
measure["id"] = measure["variable"].str.extract("(\d)")

c:\users\luisa bez\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

c:\users\luisa bez\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [183]:
ingredient

          variable              value id
21  strIngredient1            Bourbon  1
22  strIngredient2  Angostura bitters  2
23  strIngredient3              Sugar  3
24  strIngredient4              Water  4

In [184]:
measure

       variable     value id
36  strMeasure1    4.5 cL  1
37  strMeasure2  2 dashes  2
38  strMeasure3    1 cube  3
39  strMeasure4      dash  4

In [185]:
#Join ingredient and measure DataFrame to obtain final DataFrame
result = pd.merge(ingredient, measure, how = "inner", on = "id")
result

       variable_x            value_x id   variable_y   value_y
0  strIngredient1            Bourbon  1  strMeasure1    4.5 cL
1  strIngredient2  Angostura bitters  2  strMeasure2  2 dashes
2  strIngredient3              Sugar  3  strMeasure3    1 cube
3  strIngredient4              Water  4  strMeasure4      dash

In [186]:
#Drop and rename columns according to output csv file
result.drop(["variable_x", "variable_y", "id"], axis = 1, inplace = True)
result.columns = ["Ingredients", "Measure"]
result

         Ingredients   Measure
0            Bourbon    4.5 cL
1  Angostura bitters  2 dashes
2              Sugar    1 cube
3              Water      dash